language: php
 
php:
  - 5.4
  - 5.5
 
before_script:
  - ./tests/bin/install-apcu.sh
  - phpenv config-add tests/$TRAVIS_PHP_VERSION.ini
  - phpenv config-add tests/apc.ini
  
script:
  - cd tests/ && phpunit tests.php
